version: "3.9"
services:
  backend_db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_registration
    ports:
      - "5432:5432"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.43.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always